//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int orderID { get; set; }
        public string productID { get; set; }
        public Nullable<int> paymentID { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> discount { get; set; }
    
        public virtual order order { get; set; }
        public virtual payment payment { get; set; }
        public virtual product product { get; set; }
    }
}
