//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favourite
    {
        public int favouriteID { get; set; }
        public Nullable<int> userID { get; set; }
        public string productID { get; set; }
        public string productName { get; set; }
        public Nullable<double> price { get; set; }
        public string avatar { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
