//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.favourites = new HashSet<favourite>();
            this.feedbacks = new HashSet<feedback>();
        }
    
        public string productID { get; set; }
        public string productName { get; set; }
        public string description { get; set; }
        public string avatar { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> sale { get; set; }
        public Nullable<double> totalStart { get; set; }
        public Nullable<int> totalFeedback { get; set; }
        public Nullable<int> totalOrder { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
        public Nullable<System.DateTime> updateAt { get; set; }
        public string categoryID { get; set; }
        public string subcategoryID { get; set; }
        public Nullable<int> authorID { get; set; }
        public string supplierID { get; set; }
    
        public virtual author author { get; set; }
        public virtual bill bill { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favourite> favourites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback> feedbacks { get; set; }
        public virtual subcategory subcategory { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
